### ISSUE TITLE
Compilation error, Platformer.n64 cannot be created.

### ISSUE THREAD

**Issue by kimpark2000** [lambertjamesd/platformer64#1]
![picture](https://github.com/user-attachments/assets/ddd01c1d-df72-4583-8e02-5e666ec84fd3)

root@DESKTOP-1HNSSTB:/mnt/c/platformer# make
spicy --toolchain-prefix=mips-n64- -s 9 -r platformer.n64 src/spec
ERRO[0000] Error: spicy.LinkSpec: Error running 'mips-n64-ld': exit status 1: mips-n64-ld: Error: unable to disambiguate: -nostartfiles (did you mean --nostartfiles ?)
make: *** [Makefile:91: platformer.n64] Error 1

I kept trying to create platformer.n64,
A compilation error occurs.

How do I solve this?

The above issue has been resolved.

**Comment by kimpark2000** [comment]
root@DESKTOP-1HNSSTB:/mnt/c/platformer64# make
spicy --toolchain-prefix=mips32-elf- -s 9 -r platformer.n64 src/spec
ERRO[0000] Error: spicy.LinkSpec: Error running 'mips32-elf-ld': exit status 1: mips32-elf-ld: codesegment.o: in function `meshFaceCapsuleContactPoint':
(.text+0x177c): undefined reference to `fabs'
mips32-elf-ld: codesegment.o: in function `spherecastPlane':
(.text+0x2a38): undefined reference to `fabs'
mips32-elf-ld: codesegment.o: in function `slideContactPointEdge':
(.text+0x3e70): undefined reference to `fabs'
make: *** [Makefile:91: platformer.n64] Error 1

I don't understand why the message "undefined reference" appears.

![picture2](https://github.com/user-attachments/assets/b081e71f-762f-4a63-ba69-ddde542861f9)

**Comment by lambertjamesd** [comment]
This project never really got anywhere. I don't plan on working on it anymore.

**Comment by kimpark2000** [comment]
thank you for letting me know ^^
